package com.yyw.android.bestnow.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APP".
 */
public class App {

    private String packageName;
    private String label;
    private Boolean shouldStatistic;
    private Boolean isLimit;
    private Long limitTime;

    public App() {
    }

    public App(String packageName) {
        this.packageName = packageName;
    }

    public App(String packageName, String label, Boolean shouldStatistic, Boolean isLimit, Long limitTime) {
        this.packageName = packageName;
        this.label = label;
        this.shouldStatistic = shouldStatistic;
        this.isLimit = isLimit;
        this.limitTime = limitTime;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Boolean getShouldStatistic() {
        return shouldStatistic;
    }

    public void setShouldStatistic(Boolean shouldStatistic) {
        this.shouldStatistic = shouldStatistic;
    }

    public Boolean getIsLimit() {
        return isLimit;
    }

    public void setIsLimit(Boolean isLimit) {
        this.isLimit = isLimit;
    }

    public Long getLimitTime() {
        return limitTime;
    }

    public void setLimitTime(Long limitTime) {
        this.limitTime = limitTime;
    }

}
