package com.yyw.android.bestnow.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "APP_USAGE".
 */
public class AppUsage {

    private String packageName;
    private String label;
    private Long UsageTimeSinceBase;
    private Integer totalLaunchCount;
    private Long totalUsageTime;
    private Long lastTimeUsed;
    private Long startRecordTime;
    private Long updateTime;

    public AppUsage() {
    }

    public AppUsage(String packageName) {
        this.packageName = packageName;
    }

    public AppUsage(String packageName, String label, Long UsageTimeSinceBase, Integer totalLaunchCount, Long totalUsageTime, Long lastTimeUsed, Long startRecordTime, Long updateTime) {
        this.packageName = packageName;
        this.label = label;
        this.UsageTimeSinceBase = UsageTimeSinceBase;
        this.totalLaunchCount = totalLaunchCount;
        this.totalUsageTime = totalUsageTime;
        this.lastTimeUsed = lastTimeUsed;
        this.startRecordTime = startRecordTime;
        this.updateTime = updateTime;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Long getUsageTimeSinceBase() {
        return UsageTimeSinceBase;
    }

    public void setUsageTimeSinceBase(Long UsageTimeSinceBase) {
        this.UsageTimeSinceBase = UsageTimeSinceBase;
    }

    public Integer getTotalLaunchCount() {
        return totalLaunchCount;
    }

    public void setTotalLaunchCount(Integer totalLaunchCount) {
        this.totalLaunchCount = totalLaunchCount;
    }

    public Long getTotalUsageTime() {
        return totalUsageTime;
    }

    public void setTotalUsageTime(Long totalUsageTime) {
        this.totalUsageTime = totalUsageTime;
    }

    public Long getLastTimeUsed() {
        return lastTimeUsed;
    }

    public void setLastTimeUsed(Long lastTimeUsed) {
        this.lastTimeUsed = lastTimeUsed;
    }

    public Long getStartRecordTime() {
        return startRecordTime;
    }

    public void setStartRecordTime(Long startRecordTime) {
        this.startRecordTime = startRecordTime;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

}
