package com.yyw.android.bestnow.data.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yyw.android.bestnow.data.dao.AppUsage;
import com.yyw.android.bestnow.data.dao.PerHourUsage;

import com.yyw.android.bestnow.data.dao.AppUsageDao;
import com.yyw.android.bestnow.data.dao.PerHourUsageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appUsageDaoConfig;
    private final DaoConfig perHourUsageDaoConfig;

    private final AppUsageDao appUsageDao;
    private final PerHourUsageDao perHourUsageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appUsageDaoConfig = daoConfigMap.get(AppUsageDao.class).clone();
        appUsageDaoConfig.initIdentityScope(type);

        perHourUsageDaoConfig = daoConfigMap.get(PerHourUsageDao.class).clone();
        perHourUsageDaoConfig.initIdentityScope(type);

        appUsageDao = new AppUsageDao(appUsageDaoConfig, this);
        perHourUsageDao = new PerHourUsageDao(perHourUsageDaoConfig, this);

        registerDao(AppUsage.class, appUsageDao);
        registerDao(PerHourUsage.class, perHourUsageDao);
    }
    
    public void clear() {
        appUsageDaoConfig.getIdentityScope().clear();
        perHourUsageDaoConfig.getIdentityScope().clear();
    }

    public AppUsageDao getAppUsageDao() {
        return appUsageDao;
    }

    public PerHourUsageDao getPerHourUsageDao() {
        return perHourUsageDao;
    }

}
