package com.yyw.android.bestnow.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PER_HOUR_USAGE".
 */
public class PerHourUsage {

    private Long id;
    private String packageName;
    private Long time;
    private String formatTime;
    private Integer launchCount;
    private Long usageTime;
    private String date;
    private Integer hour;

    public PerHourUsage() {
    }

    public PerHourUsage(Long id) {
        this.id = id;
    }

    public PerHourUsage(Long id, String packageName, Long time, String formatTime, Integer launchCount, Long usageTime, String date, Integer hour) {
        this.id = id;
        this.packageName = packageName;
        this.time = time;
        this.formatTime = formatTime;
        this.launchCount = launchCount;
        this.usageTime = usageTime;
        this.date = date;
        this.hour = hour;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getFormatTime() {
        return formatTime;
    }

    public void setFormatTime(String formatTime) {
        this.formatTime = formatTime;
    }

    public Integer getLaunchCount() {
        return launchCount;
    }

    public void setLaunchCount(Integer launchCount) {
        this.launchCount = launchCount;
    }

    public Long getUsageTime() {
        return usageTime;
    }

    public void setUsageTime(Long usageTime) {
        this.usageTime = usageTime;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getHour() {
        return hour;
    }

    public void setHour(Integer hour) {
        this.hour = hour;
    }

}
