package com.yyw.android.bestnow.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "PER_HOUR_USAGE".
 */
public class PerHourUsage {

    private Long id;
    private String packageName;
    private Long time;
    private Integer launchCount;
    private Long usageTime;

    public PerHourUsage() {
    }

    public PerHourUsage(Long id) {
        this.id = id;
    }

    public PerHourUsage(Long id, String packageName, Long time, Integer launchCount, Long usageTime) {
        this.id = id;
        this.packageName = packageName;
        this.time = time;
        this.launchCount = launchCount;
        this.usageTime = usageTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getLaunchCount() {
        return launchCount;
    }

    public void setLaunchCount(Integer launchCount) {
        this.launchCount = launchCount;
    }

    public Long getUsageTime() {
        return usageTime;
    }

    public void setUsageTime(Long usageTime) {
        this.usageTime = usageTime;
    }

}
